name: Deploy Simplified Backend to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install flask flask-cors gunicorn
        
    - name: Test app
      run: |
        cd backend
        python -c "from app_azure import app; print('✅ App works!')"
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configure Azure Web App
      run: |
        az webapp config set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --linux-fx-version "PYTHON|3.11" \
          --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app_azure:app"
        
        az webapp config appsettings set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --settings \
            META_APP_ID="1879578119651644" \
            META_APP_SECRET="f79b3350f43751d6139e1b29a232cbf3" \
            OPENAI_API_KEY="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" \
            JWT_SECRET_KEY="secure-jwt-key-2024"
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'igshop-dev-yjhtoi-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend' 