name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Flask app import
      run: |
        cd backend
        python -c "
        import os
        os.environ['META_APP_ID'] = 'test'
        os.environ['META_APP_SECRET'] = 'test'
        os.environ['JWT_SECRET_KEY'] = 'test'
        os.environ['OPENAI_API_KEY'] = 'test'
        from app_simple import app
        print('✅ Flask app imports successfully')
        print(f'✅ Routes: {len(list(app.url_map.iter_rules()))} routes configured')
        "
        
    - name: Create deployment package
      run: |
        cd backend
        # Remove test files and cache
        rm -rf __pycache__
        rm -rf .pytest_cache
        rm -f test_*.py
        
        # Create a startup script for Azure
        cat > startup.py << 'EOF'
        import os
        import sys
        
        # Add current directory to Python path
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        
        from app_simple import app
        
        if __name__ == "__main__":
            port = int(os.environ.get("PORT", 8000))
            app.run(host="0.0.0.0", port=port, debug=False)
        EOF
        
        # Create requirements file for Azure
        echo "Creating requirements.txt for Azure..."
        ls -la
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'igshop-dev-yjhtoi-api'  # Your actual Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend'
        startup-command: 'python startup.py'

    - name: Test deployment
      run: |
        echo "Deployment completed!"
        echo "Backend should be available at: https://igshop-dev-yjhtoi-api.azurewebsites.net"
        echo "Health check: https://igshop-dev-yjhtoi-api.azurewebsites.net/health" 