name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Flask app import
      run: |
        cd backend
        python -c "
        import os
        os.environ['META_APP_ID'] = 'test'
        os.environ['META_APP_SECRET'] = 'test'
        os.environ['JWT_SECRET_KEY'] = 'test'
        os.environ['OPENAI_API_KEY'] = 'test'
        from app_simple import app
        print('✅ Flask app imports successfully')
        print(f'✅ Routes: {len(list(app.url_map.iter_rules()))} routes configured')
        "
    
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configure Azure Web App for Python
      run: |
        # Set the runtime stack to Python 3.11
        az webapp config set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --linux-fx-version "PYTHON|3.11"
        
        # Configure startup command
        az webapp config set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app_simple:app"
        
        # Enable build automation
        az webapp config appsettings set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
        
    - name: Create deployment package
      run: |
        cd backend
        # Remove test files and cache
        rm -rf __pycache__
        rm -rf .pytest_cache
        rm -f test_*.py
        
        # Ensure requirements.txt is present
        if [ ! -f requirements.txt ]; then
          echo "Error: requirements.txt not found!"
          exit 1
        fi
        
        echo "✅ Deployment package prepared"
        echo "Files to deploy:"
        ls -la
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'igshop-dev-yjhtoi-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend'

    - name: Test deployment
      run: |
        echo "Deployment completed!"
        echo "Backend should be available at: https://igshop-dev-yjhtoi-api.azurewebsites.net"
        echo "Health check: https://igshop-dev-yjhtoi-api.azurewebsites.net/health"
        
        # Wait a bit for the app to start
        sleep 30
        
        # Test the health endpoint
        curl -f https://igshop-dev-yjhtoi-api.azurewebsites.net/health || echo "Health check failed (app may still be starting)" 