name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test production Flask app
      run: |
        cd backend
        python -c "
        import os
        os.environ['META_APP_ID'] = 'test'
        os.environ['JWT_SECRET_KEY'] = 'test'
        os.environ['OPENAI_API_KEY'] = 'test'
        from production_app import app
        print('✅ Production Flask app imports successfully')
        print(f'✅ Routes: {len(list(app.url_map.iter_rules()))} routes configured')
        "
    
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configure Azure Web App
      run: |
        # Set the runtime stack to Python 3.11
        az webapp config set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --linux-fx-version "PYTHON|3.11"
        
        # Configure startup command for production app
        az webapp config set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 production_app:app"
        
        # Set environment variables
        az webapp config appsettings set \
          --resource-group igshop-dev-rg-v2 \
          --name igshop-dev-yjhtoi-api \
          --settings \
            META_APP_ID="${{ secrets.META_APP_ID }}" \
            META_APP_SECRET="${{ secrets.META_APP_SECRET }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            META_REDIRECT_URI="https://igshop-dev-yjhtoi-api.azurewebsites.net/auth/instagram/callback" \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
        
    - name: Create deployment package
      run: |
        cd backend
        # Clean up unnecessary files
        rm -rf __pycache__
        rm -rf .pytest_cache
        rm -f test_*.py
        
        echo "✅ Production deployment package prepared"
        echo "Files to deploy:"
        ls -la production_app.py requirements.txt
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'igshop-dev-yjhtoi-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend'

    - name: Test deployment
      run: |
        echo "Deployment completed!"
        echo "Backend available at: https://igshop-dev-yjhtoi-api.azurewebsites.net"
        
        # Wait for the app to start
        sleep 60
        
        # Test the health endpoint
        curl -f https://igshop-dev-yjhtoi-api.azurewebsites.net/health && echo "✅ Health check passed!" || echo "❌ Health check failed" 