name: Simple Backend Deploy

on:
  push:
    branches: [production-deployment]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create deployment package
      run: |
        zip -r deployment.zip . -x "*.git*" "*.github*" "ig-shop-agent-dashboard*" "infra*" "logs*" "test_deploy*"
    
    - name: Deploy to Azure Web App using Azure CLI
      run: |
        az webapp deploy --name igshop-api --resource-group igshop-dev-rg-v2 --src-path deployment.zip --type zip
    
    - name: Restart web app
      run: |
        az webapp restart --name igshop-api --resource-group igshop-dev-rg-v2 